environment:
  global:
    WHEEL_CACHE_DIR: "%APPVEYOR_BUILD_FOLDER%\\wheels"

  matrix:
    #- PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    #- PYTHON: "C:\\Python34"

cache:
  - '%WHEEL_CACHE_DIR%'

install:
  - ps: >-
      If(!(Test-Path $env:WHEEL_CACHE_DIR)) {
        Write-Host "Downloading wheel binary dir";
        Start-Process -FilePath "git" -ArgumentList "clone https://gist.github.com/63b34431b7da72a1eec274d5f310a0ad.git $env:WHEEL_CACHE_DIR" -Wait;
      } Else {
        Write-Host "Updating wheel binary dir";
        Start-Process -FilePath "git" -ArgumentList "pull" -WorkingDirectory "$env:WHEEL_CACHE_DIR" -Wait;
      }
  - echo %PYTHON%
  - python -V; python -c 'import platform; print(platform.architecture())'

build: off

test_script:
  - echo %PYTHON%
  - python -V; python -c 'import platform; print(platform.architecture())'
