environment:
  global:
    WHEEL_CACHE_DIR: "%APPVEYOR_BUILD_FOLDER%\\wheels"

  matrix:
    #- PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    #- PYTHON: "C:\\Python34"

cache:
  - '%WHEEL_CACHE_DIR%'

# 2
install:
  - set FOO="%PYTHON%/foo"
  - ps: >-
      If(!(Test-Path $env:WHEEL_CACHE_DIR)) {
        Write-Host "Downloading wheel binary dir";
        Start-Process -FilePath "git" -ArgumentList "clone https://gist.github.com/63b34431b7da72a1eec274d5f310a0ad.git $env:WHEEL_CACHE_DIR" -Wait;
      } Else {
        Write-Host "Updating wheel binary dir";
        Start-Process -FilePath "git" -ArgumentList "pull" -WorkingDirectory "$env:WHEEL_CACHE_DIR" -Wait;
      }
  - echo %PYTHON%
  - python --version
  - python -c "import platform; print(platform.architecture())"
  - '%PYTHON%/python -c "import platform; print(platform.architecture())"'
  - '%PYTHON%/python -m easy_install "%WHEEL_CACHE_DIR%/pycurl-7.19.5.3.win-amd64-py2.7.exe"'
  - '%PYTHON%/python -c "import pycurl; print(pycurl.version)"'

build: off

test_script:
  - echo %PYTHON%
  - python --version
  - python -c "import platform; print(platform.architecture())"
  - '%PYTHON%/python -c "import platform; print(platform.architecture())"'
  - 'echo "Foo: %FOO%"'
